-- Seed: CRO Commerce 2025 - Program sesije
-- Pokreni samo za 2025 projekt!

INSERT INTO program_sessions (time_start, time_end, stage, speaker_name, topic, session_type, sort_order) VALUES
('08:00', '09:15', 'all',        NULL,                   'Registracija i uvodno obraćanje',               'networking',  0),
('09:15', '09:45', 'future',     'Marcel Majsan',         'Izgradnja povjerenja u webshop',                 'talk',       10),
('09:45', '10:15', 'future',     'Davor Španić',          'AI praktične primjene u poslovanju',             'talk',       20),
('10:15', '10:45', 'future',     NULL,                    'Panel: Logistički trendovi (DPD, BOXNOW)',        'panel',      30),
('10:15', '10:45', 'action',     'Valentino Mrazović',    'Pametno proširenje zaliha',                      'talk',       30),
('10:15', '10:45', 'wonderland', NULL,                    'Fireside #1: eCommerce osnove',                  'fireside',   30),
('10:45', '11:00', 'all',        NULL,                    'Pauza za kavu',                                  'break',      40),
('11:00', '11:30', 'future',     'Goran Tintor',          'Temijeva globalna strategija',                   'talk',       50),
('11:00', '11:30', 'action',     'Ivica Kruhek',          'AI ograničenja – provjera stvarnosti',           'talk',       50),
('11:30', '12:00', 'future',     'Nikola Ilchev',         'Analiza rasta na Balkanu',                       'talk',       60),
('11:30', '12:00', 'action',     'Petar Pavić',           'Brendiranje i strategije storytellinga',         'talk',       60),
('11:30', '12:00', 'wonderland', NULL,                    'Fireside #2: Globalna ekspanzija',               'fireside',   60),
('12:00', '12:30', 'future',     NULL,                    'Panel: Trendovi plaćanja',                       'panel',      70),
('12:00', '12:30', 'action',     'Aleksandar Ašković',    'YouTube kao prodajni kanal',                     'talk',       70),
('12:30', '13:00', 'future',     'Tomislav Bilić',        'Mjerenje UX-a',                                  'talk',       80),
('12:30', '13:00', 'action',     'Bruno Zagorščak',       'Monetizacija podcasta',                          'talk',       80),
('13:00', '13:30', 'future',     NULL,                    'Panel: Regulatorne izmjene',                     'panel',      90),
('13:00', '13:30', 'action',     'CJ VIVnetworks',        'Optimizacija affiliate marketinga',              'talk',       90),
('13:00', '13:30', 'wonderland', NULL,                    'Fireside #3: Lokalno tržište',                   'fireside',   90),
('13:30', '14:30', 'all',        NULL,                    'Ručak',                                          'break',     100),
('14:30', '15:00', 'future',     'Ivan Radić',            'No-code logistička aplikacija',                  'talk',      110),
('14:30', '15:00', 'action',     'Marko Pačar',           'Analiza tržišnih faktora',                       'talk',      110),
('15:00', '15:30', 'future',     'Goran Udošić',          'Optimizacija komunikacije',                      'talk',      120),
('15:00', '15:30', 'action',     'Marijan Zelenko',       'IT rješenja za logistiku',                       'talk',      120),
('15:00', '15:30', 'wonderland', NULL,                    'Fireside #4: B2B/B2C/B2H',                       'fireside',  120),
('15:30', '16:00', 'future',     'Miroslav Varga',        'Google Ads + AI',                                'talk',      130),
('15:30', '16:00', 'action',     'Arpad Neveri',          'Sigurnost inovacija u plaćanjima',               'talk',      130),
('16:00', '16:15', 'all',        NULL,                    'Pauza za kavu',                                  'break',     140),
('16:15', '16:45', 'future',     'Dobromir Slavov',       'AI iskustva kupovine',                           'talk',      150),
('16:15', '16:45', 'action',     'Jakov Kiš',             'CERT verifikacijska usluga',                     'talk',      150),
('16:45', '17:00', 'future',     NULL,                    'Izvlačenje nagrade',                             'networking',160),
('17:00', '17:30', 'future',     'Ivan Bildi',            'KEYNOTE: AI marketing taktike',                  'keynote',   170),
('20:00', '00:00', 'all',        NULL,                    'Afterparty (Mozaik)',                            'networking',180);

-- Seed: CRO Commerce 2025 - Troškovi
-- Nazivi i vendori su točni prema tablici

INSERT INTO budget_items (category, vendor, amount, status, notes, sort_order) VALUES
('Fotkanje eventa',                    'ramai (300+17%), goran (350+pdv)',                       800.00,   'pending', NULL,  10),
('Snimanje glavni stage i sekundarni', 'Neuralab (bez streaminga)',                            2000.00,   'pending', NULL,  20),
('Zabava / after - DJ / bend / tehnika / barmen', 'dj, barmen',                               1700.00,   'pending', NULL,  30),
('Marketing',                          'fb, gugl, hero',                                       2500.00,   'pending', NULL,  40),
('Ispomoć',                            'studenti',                                                0.00,   'pending', NULL,  50),
('Nagrade (provizije i naš tim)',       NULL,                                                   1500.00,   'pending', NULL,  60),
('Izrada materijala (grafičar)',        NULL,                                                      0.00,   'pending', NULL,  70),
('Tehnika',                            'goran dji',                                            2000.00,   'pending', NULL,  80),
('Prostor i ručak',                    NULL,                                                  11000.00,   'pending', NULL,  90),
('Trošak predavača',                   'bildi, ašković, varga, tintor',                        2000.00,   'pending', NULL, 100),
('Voditelj eventa',                    'petar štefanić (800), maja vratarić (500), dino oreški (1000)', 2300.00, 'pending', NULL, 110),
('Prodaja ulaznica (troškovi)',         'kartične provizije',                                    300.00,   'pending', NULL, 120),
('Leon materijali',                    'leon',                                                    0.00,   'pending', NULL, 130),
('Novinar/izvještaj',                  'goran (pr i izvještaj)',                               1000.00,   'pending', NULL, 140),
('Snimanje teasera na konfi',          'justa (600+članstvo)',                                 1000.00,   'pending', NULL, 150),
('Ostali troškovi',                    'barske, frižider, pizze',                               800.00,   'pending', NULL, 160),
('PR agencija',                        NULL,                                                      0.00,   'cancelled', NULL, 170),
('Community management',               NULL,                                                      0.00,   'cancelled', NULL, 180);
